### ISSUE TITLE
Change command line

### ISSUE THREAD

**Issue by Rnaock** [JCluzet/42_GradeMe#2]
On school linux looks like we have to use this 
`bash -c "$(curl https://grademe.fr)"`
and no this :
`bash -c "$(curl grademe.fr)"`

**Comment by JCluzet** [comment]
Indeed the link was not working since yesterday 2:04 am on Linux.
This is due to a change on the SSL of the GradeMe site for more security.

Thanks to your feedback I just changed the link everywhere it was available. Thanks again!
