### ISSUE TITLE
It's segfaulting when running

### ISSUE THREAD

**Issue by mdabir1203** [JCluzet/42_GradeMe#21]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/66947064/216248277-e19dcaf1-bb63-4c26-84a1-b2c9089145dd.png">

**Comment by mdabir1203** [comment]
It happens when you choose the students part. But now after trying couple of times it worked

**Comment by bspinheiro** [comment]
By debugging the files, one reach to the segfault if there is no USER environment variable set. To avoid the error, just type in the terminal:

```shell
export USER='student'; 
``` 

And try again :)

**Comment by JCluzet** [comment]
Hey @bspinheiro ! Thanks a lot for taking the time to find this problem
I fixed the problem with the last push :)

**Comment by mdabir1203** [comment]
@bspinheiro !_!
