### ISSUE TITLE
42_EXAM not working

### ISSUE THREAD

**Issue by cezou** [JCluzet/42_GradeMe#32]
Can't run the command and go to 42_EXAM
![image](https://github.com/JCluzet/42_GradeMe/assets/76022382/b253f036-3416-4acd-bce3-84679aab131c)

**Comment by Dustcream** [comment]
Same for me

**Comment by JCluzet** [comment]
Sorry, I work actually on it

**Comment by JCluzet** [comment]
I come back when it's good

**Comment by JCluzet** [comment]
is it fix ?

**Comment by Dustcream** [comment]
yep, seems fix, it's working again, thx!!
